### ISSUE TITLE
Reticle

### ISSUE THREAD

**Issue by fluffywaffles** [Executable-Games/We-Havent-Picked-A-Name#15]
We need some form of reusable reticle for at least 2 purposes:
1. Indicating which character's #10 MoveList is being displayed during player turn
2. Indicated which enemy is currently being targeted by a player attack

**Comment by dabomb2654** [comment]
:+1: I'm thinking a sketch-like arrow that points to the character/enemy, and then keeping all menus in the relative foreground, in a Pokemon-esque fashion.
