### ISSUE TITLE
Remove 'Feature' Label

### ISSUE THREAD

**Issue by fluffywaffles** [Executable-Games/We-Havent-Picked-A-Name#17]
I don't think Feature is a useful label. Most issues are going to be 'feature' issues in our project. Let's remove that label and use the orange label color for a different purpose.

**Comment by fluffywaffles** [comment]
Feel free to weigh in if you feel strongly otherwise, @Executable-Games/core 

If there's not any opposition, I'm just going to remove it in a bit because right now all of our issues would just say "Feature" and it's not a useful label if it's literally everything.

**Comment by Skim74** [comment]
:+1:

**Comment by aaronkarp123** [comment]
Sounds good to me!

**Comment by fluffywaffles** [comment]
Done & done
