### ISSUE TITLE
We should do PRs and Code Reviews

### ISSUE THREAD

**Issue by fluffywaffles** [Executable-Games/We-Havent-Picked-A-Name#25]
@Executable-Games/core I have a proposal.

I don't know if you guys have done Pull Requests and Code Reviews before, but basically the concept is this: when you finish work on a branch, you make a Pull Request on GitHub from your branch back into the master branch. Two other team members have to perform a Code Review (look over and comment on / suggest improvements to your code), and once they have both given it a :+1: one of them will close the PR and merge your work into master.

This helps keep a fairly standard quality across our codebase and makes sure that at least 3 people always understand any given piece of functionality that we're adding to our game.

**Comment by Skim74** [comment]
:+1:

**Comment by dabomb2654** [comment]
:+1:
