### ISSUE TITLE
Attacks

### ISSUE THREAD

**Issue by Skim74** [Executable-Games/We-Havent-Picked-A-Name#8]
- Make special purpose scripts based on different types of "moves"
- Attack base component, which handles grabbing the health from a target and causing health effects, cooldowns, etc - universal stuff
- MoveList component, which maybe (?) should be a part of Unit, which will keep track of the Moves that a Unit has access to

**BasicAttack component:**
An implementation of an Attack that just does some simple damage and not much else, has 100% chance to hit, etc.
**SpecialAttack component**
An implementation of an Attack that can cause Effects, has variable damage (potentially dependent upon Unit level?), has variable accuracy, and is in general a lot cooler than BasicAttack but still based on the same principle. BasicAttack is a good smoke test; SpecialAttack is what we will probably actually use for our characters' Attacks
**Inside of Scripts there's a Combat folder**
**Inside of Combat we can make an Attacks folder**
**Inside of Attacks we can have Unit Type folders**
And in those folders we can define all the cool attacks different units can/do have

**Comment by fluffywaffles** [comment]
Let's separate out the different features that are a part of Attacks into their own issues, and give it a label

**Comment by fluffywaffles** [comment]
See #10 #11 #12 #14
